# -*- coding: utf-8 -*-
"""21BCE029_PRAC7_DM_apriory_general.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1CqEwQjyXH8cj68i8hLh6fXS0in0TUm
"""

import numpy as np
import pandas as pd

# data = pd.read_csv('items.csv')
# data.head()

# import csv
# data = set()

# I='items.csv'
# # Read the CSV file and extract unique items
# with open(I, 'r') as file:
#     reader = csv.reader(file)
#     for row in reader:
#         items = row[1].split(',')
#         data.update(items)


# data.remove('Itemsbought')
# data=list(data)
# print("Unique items:", data)

# data = [
#         ["T1", ["Beer", "Nuts", "Diaper"]],
#         ["T2", ["Beer", "Coffee", "Diaper"]],
#         ["T3", ["Beer", "Diaper", "Eggs"]],
#         ["T4", ["Nuts", "Eggs", "Milk"]],
#         ["T5", ["Nuts", "Coffee", "Diaper", "Eggs", "Milk"]]
#         ]

data=[
        ["T1", ["i1","i2","i5"]],
        ["T2", ["i2","i4"]],
        ["T3", ["i2","i3"]],
        ["T4", ["i1","i2","i4"]],
        ["T5", ["i1","i3"]],
        ["T6", ["i2","i3"]],
        ["T7", ["i1","i3"]],
        ["T8", ["i1","i2","i3","i5"]],
        ["T9", ["i1","i2","i3"]]
]

init = []
for i in data:
    for q in i[1]:
        if(q not in init):
            init.append(q)
init = sorted(init)
print(init)

sp = 0.5
con = 0.4

s = int(sp*len(init))
s=2

from collections import Counter

c = Counter()
for i in init:
    for d in data:
        if(i in d[1]):
            c[i]+=1
print("C1:")
for i in c:
    print(str([i])+": "+str(c[i]))
print()

l = Counter()
for i in c:
    if(c[i] >= s):
        l[frozenset([i])]+=c[i]
print("L1:")
for i in l:
    print(str(list(i))+": "+str(l[i]))
print()

pl = l
pos = 1
for count in range (2,1000):
    nc = set()
    temp = list(l)
    for i in range(0,len(temp)):
        for j in range(i+1,len(temp)):
            t = temp[i].union(temp[j])
            if(len(t) == count):
                nc.add(temp[i].union(temp[j]))
    nc = list(nc)
    c = Counter()
    for i in nc:
        c[i] = 0
        for q in data:
            temp = set(q[1])
            if(i.issubset(temp)):
                c[i]+=1
    print("C"+str(count)+":")
    for i in c:
        print(str(list(i))+": "+str(c[i]))
    print()
    l = Counter()
    for i in c:
        if(c[i] >= s):
            l[i]+=c[i]
    print("L"+str(count)+":")
    for i in l:
        print(str(list(i))+": "+str(l[i]))
    print()
    if(len(l) == 0):
        break
    pl = l
    pos = count
print("Result: ")
print("L"+str(pos)+":")
for i in pl:
    print(str(list(i))+": "+str(pl[i]))
print()

# Assoccation rule mining

from itertools import combinations
for l in pl:
    c = [frozenset(q) for q in combinations(l,len(l)-1)]
    mmax = 0
    print(c)
    for a in c:
        b = l-a
        ab = l
        sab = 0
        sa = 0
        sb = 0
        for q in data:
            temp = set(q[1])
            if(a.issubset(temp)):
                sa+=1
            if(b.issubset(temp)):
                sb+=1
            if(ab.issubset(temp)):
                sab+=1
        temp = sab/sa*100
        if(temp > mmax):
            mmax = temp
        temp = sab/sb*100
        if(temp > mmax):
            mmax = temp
        print(str(list(a))+" -> "+str(list(b))+" = "+str(sab/sa*100)+"%")
        print(str(list(b))+" -> "+str(list(a))+" = "+str(sab/sb*100)+"%")

