# -*- coding: utf-8 -*-
"""DM4_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC18iYz_99CfhtOba7K4YC0ynAp_wOrt
"""

print("Practical 4")

import pandas as pd

data=pd.read_csv("/content/train.csv")
data

#first is ignoring tupple
def ignorTupple(data):
  df = pd.DataFrame(data)

  # Step 1: Remove rows with null values in the 'age' column
  df = df.dropna(subset=['Age'])

  # Step 2: Remove rows where 'age' is not numeric
  df = df[df['Age'].astype(int) == df['Age']] #conparing original value after converting it into (int)

  # Step 3: Remove rows where 'age' is not greater than 0
  df = df[df['Age'] > 0]

  # Saving the resulting DataFrame
  df.to_csv('dfWithIgnoredTupple.csv', index=False)

ignorTupple(data)
# dfWithIgnoredTupple.head()

def fillWithMean(dfOriginal,df):
  df_male=df[df["Sex"]=="male"]
  df_female=df[df["Sex"]=="female"]

  mean_male=df_male["Age"].mean().astype(int)
  print(mean_male)

  mean_female=df_female["Age"].mean().astype(int)
  print(mean_female)
  # print(list(dfOriginal["Age"]))
  for index, value in dfOriginal['Age'].items():
    # if pd.isnull(value) or not pd.to_numeric(value, errors='coerce') > 0:
    if ((value<1.00) or (value<0.00) or (pd.isnull(value))):
      if(dfOriginal["Sex"][index] == "male"):
        dfOriginal.at[index,"Age"]=mean_male
      else:
        dfOriginal.at[index,"Age"]=mean_female
    # print(dfOriginal["Age"][index])
      # Replace null values, non-numeric values, and values <= 0 with a new value
      # df.at[index, 'Age'] = new_value  # or df.loc[index, 'Age'] = new_value



  # print(dfOriginal)



  df_male.to_csv('male.csv', index=False)
  df_female.to_csv('female.csv', index=False)
  dfOriginal
  return dfOriginal

dfOriginal=pd.DataFrame(data)
df=pd.read_csv("/content/dfWithIgnoredTupple.csv")

dfOriginal=fillWithMean(dfOriginal,df)

dfOriginal



def Fillwithmanual(dfOriginal,given_col,given_val):
  for index, value in dfOriginal['Age'].items():
    dfOriginal.at[index,"Age"]=given_val


  return dfOriginal

dfOriginal=pd.DataFrame(data)
given_col=str(input())
given_val=(input())
if(given_col not in (dfOriginal.columns)):
  print("Not present")

# print(type(given_col))
# print(df[given_col].dtype)
# print(type(df[given_col][0]))
# if(type(given_col) != (type(df[given_col][0].item()))):
#   print("Invalid data type")

dfOriginal=Fillwithmanual(dfOriginal,given_col,given_val)

dfOriginal

23