# -*- coding: utf-8 -*-
"""DM_6_PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doqB2N-BKbo5wSX6DWbswQJ6UM7rNZ_i
"""

print("prac 6")

import math
import numpy as np

def mean(lst):
    sum=0
    for i in lst:
      sum+=i
    mean=(sum)/len(lst)
    return mean

def cov(x,y):
  n=len(x)
  xmean=mean(x)
  ymean=mean(y)

  mul=0
  for i in range(n):
    mul=mul+((x[i]-xmean)*(y[i]-ymean))

  mul=(mul/(n-1))
  return mul

def eigenval(x,y,z,w):
  a=1
  b=(-1)*x+(-1)*w
  c=(x*w)-(y*z)

  print(a,b,c)
  sqrt=math.sqrt((b*b) - (4*a*c))
  return (((-1)*b+sqrt)/2,((-1)*b-sqrt)/2)

def norm(lst):
  deno=0
  for i in lst:
    deno+=(i*i)

  deno=math.sqrt(deno)

  normalized=[]
  for i in lst:
    normalized.append(i/(deno))

  return normalized

# x=[4,8,13,7]
# y=[11,4,5,14]

# 78
# 80
# 81
# 82
# 84
# 86

# 126
# 128
# 127
# 130
# 130
# 132

x=[78,80,81,82,84,86]
y=[126,128,127,130,130,132]

xmean=mean(x)
ymean=mean(y)
print(xmean,ymean)

a=(cov(x,x))
b=(cov(x,y))
c=(cov(y,x))
d=(cov(y,y))

# print(a,b,c,d)

s=[]
s.append(list([a,b]))
s.append(list([c,d]))

print("covarience matrix",s)

lem1,lem2=eigenval(a,b,c,d)
print(lem1,lem2)

lem=max(lem1,lem2)

# a-=lem
# d-=lem

# print(a,b,c,d)

# a=int(a)
# b=int(b)
# c=int(c)
# d=int(d)

print(a,b,c,d)

eighenvec=[]
eighenvec.append((-1)*(b))
eighenvec.append(a-lem)

print(eighenvec)





nor_eighen_vec=norm(eighenvec)

print(nor_eighen_vec)

p1=[]
# print(x,y,xmean,ymean)
for i in range(len(x)):
  p1.append((x[i]-xmean)*(nor_eighen_vec[0]) + (y[i]-ymean)*(nor_eighen_vec[1]))


print(p1)

